export {default as Home} from "./Home/Home"
export {default as Planetas} from "./Planetas/Planetas"
export {default as Galaxias} from "./Galaxias/Galaxias"
export {default as BlackHoles} from "./BlackHoles/BlackHoles"
export {default as Historia} from "./Historia/Historia"